services:
  - type: web
    name: riday-restaurant-system
    env: docker
    plan: free
    healthCheckPath: /
    envVars:
      - key: PHP_VERSION
        value: 8.2
      - key: ENVIRONMENT  
        value: production
