services:
  - type: web
    name: restaurant-ordering-system
    env: php
    plan: free
    buildCommand: composer install --no-dev
    startCommand: php -S 0.0.0.0:$PORT -t .
    envVars:
      - key: DB_HOST
        value: dpg-your-database-host
      - key: DB_NAME  
        value: restaurant_ordering
      - key: DB_USER
        value: restaurant_ordering_user
      - key: DB_PASS
        fromDatabase:
          name: restaurant-db
          property: password
      - key: CLOUDINARY_CLOUD_NAME
        value: your-cloud-name
      - key: CLOUDINARY_API_KEY
        value: your-api-key
      - key: CLOUDINARY_API_SECRET
        value: your-api-secret

  - type: pserv
    name: restaurant-db
    env: postgresql
    plan: free
    databaseName: restaurant_ordering
    databaseUser: restaurant_ordering_user