services:
  - type: web
    name: restaurant-ordering
    env: php
    plan: free
    buildCommand: composer install --no-dev --optimize-autoloader
    startCommand: php -S 0.0.0.0:$PORT -t .
    envVars:
      - key: DB_HOST
        value: YOUR_DB_HOST
      - key: DB_NAME
        value: YOUR_DB_NAME
      - key: DB_USER
        value: YOUR_DB_USER
      - key: DB_PASS
        value: YOUR_DB_PASS
      - key: CLOUDINARY_CLOUD_NAME
        value: YOUR_CLOUDINARY_CLOUD_NAME
      - key: CLOUDINARY_API_KEY
        value: YOUR_CLOUDINARY_API_KEY
      - key: CLOUDINARY_API_SECRET
        value: YOUR_CLOUDINARY_API_SECRET
