services:
  - type: web
    name: restaurant-ordering-system
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: DB_HOST
        fromDatabase:
          name: restaurant-db
          property: host
      - key: DB_NAME  
        value: restaurant_ordering
      - key: DB_USER
        fromDatabase:
          name: restaurant-db
          property: user
      - key: DB_PASS
        fromDatabase:
          name: restaurant-db
          property: password
      - key: DB_PORT
        value: "5432"
      - key: CLOUDINARY_CLOUD_NAME
        value: ""
      - key: CLOUDINARY_API_KEY
        value: ""
      - key: CLOUDINARY_API_SECRET
        value: ""

databases:
  - name: restaurant-db
    plan: free
    databaseName: restaurant_ordering
    user: restaurant_ordering_user