services:
  - type: web
    name: riday-restaurant-system
    env: php
    plan: free
    buildCommand: |
      # Install composer dependencies
      curl -sS https://getcomposer.org/installer | php
      php composer.phar install --no-dev --optimize-autoloader || true
    startCommand: php -S 0.0.0.0:$PORT -t .
    envVars:
      - key: PORT
        generateValue: true
      - key: DB_HOST
        sync: false
      - key: DB_NAME  
        sync: false
      - key: DB_USER
        sync: false
      - key: DB_PASS
        sync: false
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
